### ISSUE TITLE
Service not found when setting up a plugin

### ISSUE THREAD

**Issue by MinDBreaK** [crayner/CKEditor#7]
It appears that if I add a new plugin, it throws this beautiful red screen:
``` 
(1/1) ServiceNotFoundException
You have requested a non-existent service "hillrange_ck_editor.plugin_manager".
```

And here is my config :
```yml
hillrange_ckeditor:
    plugins:
        imageUploader:
            path: "/path/to/"
            filename: "imageUploader.js"
```

However it is working fine if i upload the file directly in the lib directory.

Symfony 4.0
PHP 7.2.3

**Comment by crayner** [comment]
@MinDBreaK 
Thanks for the details and sorry about the red screen.  Version 1.0.1 has fixed this, but I am still waiting for the flex recipe to be approved for version 1.0.0, so that will not yet work correctly with composer.
## Fix
Corrected calls to PluginManager and TemplateManager in HillrangeCKEditorExtension.php to suit Symfony 3.4+ when setting up details for configuration.

Your config also has a syntax error as well:

```
hillrange_ckeditor:
    plugins:
        imageUploader:
            path: "/path/to/"
            filename: "imageUploader.js"
```
**Replace** 

> hillrange_ckeditor:

**with**

> hillrange_ck_editor:

A full example from my app, contained within my *config/packages/hillrange_ck_editor.yaml* file is:
```
hillrange_ck_editor:
    default_config: normal
    configs:
        normal:
            toolbar:
                - ['Styles','Format','Font','FontSize']
                - '/'
                - ['Bold','Italic','Underline','StrikeThrough','-','Undo','Redo','-','Cut','Copy','Paste','PasteText','Find','Replace','-','Outdent','Indent','-','Print','-','Maximize']
                - '/'
                - ['NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock']
                - ['Image','Table','-','Link','Smiley','TextColor','BGColor','Source']
            uiColor: "ddcccc"
        simple_toolbar:
            toolbar:
                - ['Bold', 'Italic', 'Strike', 'Link']
                - ['BulletedList', 'NumberedList', '-', 'Outdent', 'Indent']
                - ['Copy', 'Paste', 'PasteFromWord', '-', 'Undo', 'Redo']
                - ['Source']
    plugins:
        imageUploader:
            path: "/admin/"
            filename: "imageUploader.js"
```
When flex is working correctly a default copy of this file will be added to your app *config/packages* directory.  Let me know if you continue to see an error with this and I will investigate further.

Craig
